# Generated by Django 4.2.6 on 2023-10-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emoployees',
            new_name='Employees',
        ),
    ]
